# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

BV_SI <- function(y, e, g, w, C, s, q, maxSteps, hatM, hatR0, hatRStar, hatata, hatInvSigM0, hatInvTauSq0, hatInvTauSqStar, hatInvTauSq1, hatInvTauSq2, hatPi, hatPi1, hatLambdaSq0, hatLambdaSqStar, hatLambdaSq1, hatLambdaSq2, hatSigmaSq, a0, b0, aStar, bStar, a1, b1, a2, b2, alpha, gamma, mu1, mu2, nu1, nu2, progress) {
    .Call(`_Blend_BV_SI`, y, e, g, w, C, s, q, maxSteps, hatM, hatR0, hatRStar, hatata, hatInvSigM0, hatInvTauSq0, hatInvTauSqStar, hatInvTauSq1, hatInvTauSq2, hatPi, hatPi1, hatLambdaSq0, hatLambdaSqStar, hatLambdaSq1, hatLambdaSq2, hatSigmaSq, a0, b0, aStar, bStar, a1, b1, a2, b2, alpha, gamma, mu1, mu2, nu1, nu2, progress)
}

BV <- function(xx, y, W, C, s, q, maxSteps, hatBeta, hatAlpha, hatata, hatInvTauSq, hatInvTauSq1, hatInvTauSq2, invSigAlpha0, hatPi, hatPi1, hatLambdaSqStar, hatLambdaSq1, hatLambdaSq2, hatSigmaSq, aStar, bStar, a1, b1, a2, b2, alpha, gamma, mu1, mu2, nu1, nu2, progress) {
    .Call(`_Blend_BV`, xx, y, W, C, s, q, maxSteps, hatBeta, hatAlpha, hatata, hatInvTauSq, hatInvTauSq1, hatInvTauSq2, invSigAlpha0, hatPi, hatPi1, hatLambdaSqStar, hatLambdaSq1, hatLambdaSq2, hatSigmaSq, aStar, bStar, a1, b1, a2, b2, alpha, gamma, mu1, mu2, nu1, nu2, progress)
}

BVSS_SI <- function(y, e, g, w, C, s, q, maxSteps, hatM, hatR0, hatata, hatRStar, hatInvSigM0, hatInvTauSq0, hatInvTauSqStar, hatInvTauSq1, hatInvTauSq2, hatPi0, hatPiStar, hatPi, hatPi1, hatLambdaSq0, hatLambdaSqStar, hatLambdaSq1, hatLambdaSq2, hatSigmaSq, a0, b0, aStar, bStar, a1, b1, a2, b2, alpha, gamma, mu0, muStar, mu1, mu2, nu0, nuStar, nu1, nu2, progress) {
    .Call(`_Blend_BVSS_SI`, y, e, g, w, C, s, q, maxSteps, hatM, hatR0, hatata, hatRStar, hatInvSigM0, hatInvTauSq0, hatInvTauSqStar, hatInvTauSq1, hatInvTauSq2, hatPi0, hatPiStar, hatPi, hatPi1, hatLambdaSq0, hatLambdaSqStar, hatLambdaSq1, hatLambdaSq2, hatSigmaSq, a0, b0, aStar, bStar, a1, b1, a2, b2, alpha, gamma, mu0, muStar, mu1, mu2, nu0, nuStar, nu1, nu2, progress)
}

BVSS <- function(y, W, xx, C, s, q, maxSteps, hatAlpha, hatBeta, hatata, hatInvTauSqStar, hatInvTauSq1, hatInvTauSq2, invSigAlpha0, hatPiStar, hatPi, hatPi1, hatLambdaSqStar, hatLambdaSq1, hatLambdaSq2, hatSigmaSq, aStar, bStar, a1, b1, a2, b2, alpha, gamma, sh1, sh0, mu1, nu1, mu2, nu2, progress) {
    .Call(`_Blend_BVSS`, y, W, xx, C, s, q, maxSteps, hatAlpha, hatBeta, hatata, hatInvTauSqStar, hatInvTauSq1, hatInvTauSq2, invSigAlpha0, hatPiStar, hatPi, hatPi1, hatLambdaSqStar, hatLambdaSq1, hatLambdaSq2, hatSigmaSq, aStar, bStar, a1, b1, a2, b2, alpha, gamma, sh1, sh0, mu1, nu1, mu2, nu2, progress)
}

RBV_SI <- function(y, e, g, w, C, maxSteps, q, hatBeta, hatEta, hatAlpha, hatata, hatTau, hatV, hatSg1, hatSg2, hatSg3, hatSg4, invSigAlpha0, hatPi3, hatPi4, hatEtaSq1, hatEtaSq2, hatEtaSq3, hatEtaSq4, xi1, xi2, r1, r2, r3, r4, a, b, sh1, sh0, progress) {
    .Call(`_Blend_RBV_SI`, y, e, g, w, C, maxSteps, q, hatBeta, hatEta, hatAlpha, hatata, hatTau, hatV, hatSg1, hatSg2, hatSg3, hatSg4, invSigAlpha0, hatPi3, hatPi4, hatEtaSq1, hatEtaSq2, hatEtaSq3, hatEtaSq4, xi1, xi2, r1, r2, r3, r4, a, b, sh1, sh0, progress)
}

RBV <- function(xx, y, W, C, s, q, maxSteps, hatAlpha, hatBeta, hatata, hatTau, hatV, hatSg, hatSg3, hatSg4, invSigAlpha0, hatPi3, hatPi4, hatEtaSq, hatEtaSq3, hatEtaSq4, xi1, xi2, r, r3, r4, a, b, sh1, sh0, progress) {
    .Call(`_Blend_RBV`, xx, y, W, C, s, q, maxSteps, hatAlpha, hatBeta, hatata, hatTau, hatV, hatSg, hatSg3, hatSg4, invSigAlpha0, hatPi3, hatPi4, hatEtaSq, hatEtaSq3, hatEtaSq4, xi1, xi2, r, r3, r4, a, b, sh1, sh0, progress)
}

RBVSS_SI <- function(y, e, g, w, C, maxSteps, q, hatBeta, hatEta, hatAlpha, hatata, hatTau, hatV, hatSg1, hatSg2, hatSg3, hatSg4, invSigAlpha0, hatPi1, hatPi2, hatPi3, hatPi4, hatEtaSq1, hatEtaSq2, hatEtaSq3, hatEtaSq4, xi1, xi2, r1, r2, r3, r4, a, b, sh1, sh0, progress) {
    .Call(`_Blend_RBVSS_SI`, y, e, g, w, C, maxSteps, q, hatBeta, hatEta, hatAlpha, hatata, hatTau, hatV, hatSg1, hatSg2, hatSg3, hatSg4, invSigAlpha0, hatPi1, hatPi2, hatPi3, hatPi4, hatEtaSq1, hatEtaSq2, hatEtaSq3, hatEtaSq4, xi1, xi2, r1, r2, r3, r4, a, b, sh1, sh0, progress)
}

RBVSS <- function(xx, y, W, C, s, q, maxSteps, hatAlpha, hatBeta, hatata, hatTau, hatV, hatSg, hatSg3, hatSg4, invSigAlpha0, hatPi, hatPi3, hatPi4, hatEtaSq, hatEtaSq3, hatEtaSq4, xi1, xi2, r, r3, r4, a, b, sh1, sh0, progress) {
    .Call(`_Blend_RBVSS`, xx, y, W, C, s, q, maxSteps, hatAlpha, hatBeta, hatata, hatTau, hatV, hatSg, hatSg3, hatSg4, invSigAlpha0, hatPi, hatPi3, hatPi4, hatEtaSq, hatEtaSq3, hatEtaSq4, xi1, xi2, r, r3, r4, a, b, sh1, sh0, progress)
}

